 const products = [
  {
    id: 1,
    name: "Green",
    brand: "Otterbox",
    dic: "Mobile covers are available in a wide range of prices, depending on the material, design, and brand. They are popular among mobile device users as a way to personalize their devices and express their style and personality.",
    img: "https://cdn.shopify.com/s/files/1/0078/1032/files/otterbox-case_600x600.jpg?v=1656437931",
    price: 10,
    cat: "smartwatch",
    color: "green",
  },
  {
    id: 2,
    name: "Black",
    brand: "Smartish",
    dic: "Mobile covers come in different shapes and sizes to fit various models and brands of mobile devices. They typically cover the back and sides of the device, leaving the screen, buttons, and ports exposed for easy access. Some covers also come with additional features, such as a kickstand, a cardholder, or a battery pack.",
    img: "https://cdn.shopify.com/s/files/1/0078/1032/files/smartish_1024x1024.jpg?v=1656077533",
    price: 15,
    cat: "smartwatch",
    color: "black",
  },
  {
    id: 3,
    name: "Pink",
    brand: " Loopy",
    dic: "A phone case is a cover that protects the outside of your phone and acts as a guard to your gadget against scratches, grime, and other risks. That means it protects your electronics and extends the longevity of the device as opposed to ending its lifespan early.",
    img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/51ASC9iqTfL._SX425_.jpg",
    price: 20,
    cat: "smartwatch",
    color: "pink",
  },
  {
    id: 4,
    name: "Protector",
    brand: "JETech",
    dic: "creen protectors are typically made from materials such as tempered glass, plastic, or a combination of both. They can be transparent or colored, and may have additional features such as anti-glare or anti-fingerprint coatings",

    img: "https://olixar.com/wp-content/uploads/2021/11/Glass-Screen-Protectors.jpg",
    price: 10,
    cat: "smartwatch",
    color: "white",
  },
  {
    id: 5,
    name: "GT2 Pro",
    brand: "Huawei",
    dic: "The Huawei GT2 Pro is a smartwatch that offers a range of features designed to help users stay connected and track their fitness. The watch features a 1.39-inch AMOLED touchscreen display with a resolution of 454 x 454 pixels, and is powered by Huawei's own Kirin A1 chipset.",
    img: "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61ult08OEiL._AC_SX679_.jpg",
    price: 195,
    cat: "smartwatch",
    color: "black",
  },
  {
    id: 6,
    name: "Airpods3",
    brand: "Apple",
    dic: "the third-generation AirPods are Apple's main wireless earbuds, featuring a streamlined design, force sensor controls, Adaptive EQ, spatial audio with dynamic head tracking, a MagSafe charging case, and more",
    img: "https://d3cd3hu9wl72jo.cloudfront.net/1.d/preview/a/8/a897b718_a07ff526_AirPods-3rd.jpg",
    price: 120,
    cat: "smartwatch",
    color: "white",
  },
  {
    id: 7,
    name: " Sound X 2021",
    brand: "Huawei",
    dic: "Huawei Sound X 2021 has four 5W midrange speakers, a 50W subwoofer, a 3W tweeter, and two passive radiators. The Sound X 2021 uses a 360° all-metal sound hole and a 3D surface seamless process with a thickness of only 0.8mm.",
    img: "https://www.giztop.com/media/catalog/product/cache/dc206057cdd42d7e34b9d36e347785ca/h/u/huawei_sound_x_2021-3.jpg",
    price: 340,
    cat: "Audio",
    color: "black",
  },
  {
    id: 8,
    name: "black",
    brand: "Cat",
    dic: "A mobile cover is a protective case that is designed to fit over a mobile device such as a smartphone or tablet. These covers are typically made from a variety of materials such as plastic, silicone, leather, or metal, and are available in a wide range of colors and designs to suit personal tastes.",
    img: "https://images.dailyobjects.com/marche/product-images/1101/slick-phone-case-cover-for-iphone-13-images/Nimbus-Phone-Case-Cover-For-iPhone-13.png?tr=cm-pad_resize,v-2",
    price: 25,
    cat: "smartwatch",
    color: "black",
  },
  {
    id: 9,
    name: "screen protector",
    brand: "Anker",
    dic: "k2ld2j",
    img: "https://arrivly.com/images/tradeMark/6/privacy-screen-protector.jpg",
    price: 20,
    cat: "protector",
    color: "red",
  },
  {
    id: 10,
    name: "freebuds 5i",
    brand: "huawei",
    dic: "Features. Hi-Res Audio to Tickle your Ear HUAWEI FreeBuds 5i is Hi-Res Audio Wireless certificated, featuring a wider frequency response, full-link high-resolution sound for HD audio sources, and multiple EQs to match with a wide range of different styles, for a tailor-made listening experience.",
    img: "https://alhoot-palace.com/wp-content/uploads/2023/01/huawei-freebuds-5i-4.jpg",
    price: 160,
    cat: "protector",
    color: "silver",
  },
    {
    id: 11,
    name: "Anker 633 Magnetic Battery",
    brand: "Anker",
    dic: "Features. Hi-Res Audio to Tickle your Ear HUAWEI FreeBuds 5i is Hi-Res Audio Wireless certificated, featuring a wider frequency response, full-link high-resolution sound for HD audio sources, and multiple EQs to match with a wide range of different styles, for a tailor-made listening experience.",
    img: "https://cdn.shopify.com/s/files/1/0493/9834/9974/products/A1641011-Anker_633_Magnetic_Battery_2.png?v=1672388238",
    price: 45,
    cat: "charging",
    color: "silver",
  },
    {
    id: 12,
    name: "Razer Kraken Pro V2",
    brand: "Razzer",
    dic: "Features. Hi-Res Audio to Tickle your Ear HUAWEI FreeBuds 5i is Hi-Res Audio Wireless certificated, featuring a wider frequency response, full-link high-resolution sound for HD audio sources, and multiple EQs to match with a wide range of different styles, for a tailor-made listening experience.",
    img: "https://assets2.razerzone.com/images/pnx.assets/60ded9ab42e73d2f78db4ba59f032976/razer-kraken-v3-compatibility-500x500.png",
    price: 110,
    cat: "headset",
    color: "black",
  },
];

module.exports = products;
